# Generated by Django 4.1.7 on 2024-01-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unreturned_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_days_not_returned', models.IntegerField()),
                ('item_borrowed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recents.borrowed_item')),
            ],
        ),
    ]
