# Generated by Django 4.1.7 on 2023-12-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unreturned', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unreturned_Items',
            new_name='Unreturned_Item',
        ),
    ]
