# Generated by Django 4.1.7 on 2023-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unreturned', '0002_rename_unreturned_items_unreturned_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreturned_item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
