# Generated by Django 4.1.7 on 2023-12-28 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unreturned', '0004_unreturned_item_item_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreturned_item',
            name='item_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unreturned_item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='borrowed_item'),
        ),
    ]
