# Generated by Django 4.1.7 on 2024-01-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed_Item',
            fields=[
                ('borrow_form_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_quantity', models.IntegerField()),
                ('item_returned', models.BooleanField()),
                ('item_date_borrowed', models.DateField()),
                ('item_date_returned', models.DateField(blank=True, null=True)),
                ('item_borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
