# Generated by Django 5.0.2 on 2024-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_item',
            name='guest_course',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='borrowed_item',
            name='guest_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='borrowed_item',
            name='guest_section',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
