# Generated by Django 4.1.7 on 2023-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recents', '0003_borrowed_item_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_item',
            name='item_borrower',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
