# Generated by Django 4.1.7 on 2023-12-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_item_delete_cleaning_material_and_more'),
        ('recents', '0007_borrowed_item_id_alter_borrowed_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed_item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='borrowed_item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='borrowed_item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='borrowed_item',
            name='item_photo',
        ),
        migrations.AddField(
            model_name='borrowed_item',
            name='borrow_form_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowed_item',
            name='item_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.item'),
        ),
    ]
