# Generated by Django 4.1.7 on 2023-12-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_item_item_borrowed_quantity_and_more'),
        ('recents', '0008_remove_borrowed_item_id_remove_borrowed_item_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed_item',
            name='item_information',
        ),
        migrations.AddField(
            model_name='borrowed_item',
            name='item_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
    ]
