# Generated by Django 4.1.7 on 2024-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recents', '0009_remove_borrowed_item_item_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_item',
            name='item_date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
