# Generated by Django 4.1.7 on 2023-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning_Materials',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_category', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_category', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_category', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_category', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
            ],
        ),
    ]
