# Generated by Django 4.1.7 on 2024-01-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_photo', models.ImageField(blank=True, upload_to='item_photo')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField(blank=True, null=True)),
                ('item_borrowed_quantity', models.IntegerField(blank=True, null=True)),
                ('item_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
        ),
    ]
