# Generated by Django 4.1.7 on 2024-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_damaged_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_pristine_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
