# Generated by Django 5.0.2 on 2024-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stock_item_damaged_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=64)),
                ('guest_course', models.CharField(max_length=64)),
                ('guest_section', models.CharField(max_length=64)),
            ],
        ),
    ]
