# Generated by Django 4.1.7 on 2023-12-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cleaning_materials_cleaning_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean_Approval_Needed',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_category', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
            ],
        ),
    ]
