# Generated by Django 4.1.7 on 2023-12-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dean_approval_needed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dean_Approval_Needed',
            new_name='Dean_Approval_Needed_Item',
        ),
    ]
