# Generated by Django 5.0.2 on 2024-03-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
