# Generated by Django 5.0.2 on 2024-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_one_time_borrow',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
