# Generated by Django 4.1.7 on 2023-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_dean_approval_needed_dean_approval_needed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning_material',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dean_approval_needed_item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='furniture',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
