# Generated by Django 5.0.2 on 2024-05-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_item_item_one_time_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_category_photo',
            field=models.ImageField(blank=True, upload_to='item_category_photo'),
        ),
    ]
