# Generated by Django 4.1.7 on 2023-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cleaning_material_item_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning_material',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='cleaning_material'),
        ),
        migrations.AlterField(
            model_name='dean_approval_needed_item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='dean_item'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='furniture'),
        ),
        migrations.AlterField(
            model_name='room',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='room'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='technology'),
        ),
    ]
