# Generated by Django 4.1.7 on 2023-12-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cleaning_material_item_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('item_description', models.CharField(max_length=256)),
                ('item_total_quantity', models.IntegerField()),
                ('item_current_quantity', models.IntegerField()),
                ('item_borrowed_quantity', models.IntegerField()),
                ('item_photo', models.ImageField(blank=True, upload_to='furniture')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Cleaning_Material',
        ),
        migrations.DeleteModel(
            name='Dean_Approval_Needed_Item',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
