# Generated by Django 4.1.7 on 2023-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_item_item_borrowed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='item_photo'),
        ),
    ]
